apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxstore-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boxstore-api          # ← этот label должен совпадать с selector в Service
  template:
    metadata:
      labels:
        app: boxstore-api        # ← этот label должен совпадать с selector в Service
    spec:
      containers:
        - name: boxstore-api
          image: boxstore-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8008
